channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.2.1
- pip:
  - mlflow==2.12.2
  - cloudpickle==2.2.1
  - lz4==4.3.2
  - packaging==23.1
  - pathlib==1.0.1
  - psutil==5.9.0
  - pyyaml==6.0
  - scikit-learn==1.3.0
  - typing-extensions==4.11.0
name: mlflow-env
